name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GCC
        run: sudo apt-get update && sudo apt-get install -y build-essential clang-format

      - name: Build project
        run: make -C Array-basedStack all

      - name: Run tests
        run: make -C Array-basedStack test

      - name: Check format
        run: make -C Array-basedStack check_fmt

      - name: Upload test results (optional)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test_definite_integral
