name: CI

on:
  push:
    branches:
      - main
      - task_3.2
  pull_request:
    branches:
      - main
      - task_3.2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential clang-format

      - name: Build project
        run: make -C task_3.2 all

      - name: Run tests
        run: make -C task_3.2 test

      - name: Check format
        run: make -C task_3.2 check-format

