name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up GCC
        run: sudo apt-get install -y build-essential

      - name: Build project
        run: |
          cd Array-basedStack
          make all

      - name: Run tests
        run: |
          cd Array-basedStack
          make test
