name: Stack CI

on:

  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test stack
        run: |
          cd task_7/array-based_stack
          gcc -Wall -Wextra -Werror array-based_stack.c array-based_stack_test.c -o test
          ./test

