name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GCC
        run: sudo apt-get update && sudo apt-get install -y build-essential clang-format

      - name: Build project
        run: make all

      - name: Run tests
        run: make test

      - name: Check format
        run: make check_fmt
