name: CI

on:
  push:
    branches:
      - main  # или develop, если у вас другая основная ветка
  pull_request:
    branches:
      - main # или develop

jobs:
  build:
    runs-on: ubuntu-latest # Или другой runner, если требуется
    permissions:
      actions: read  # Необходимо для доступа к actions
      contents: read # Необходимо для checkout
    steps:
      - uses: actions/checkout@v4  # Checkout code from the repository

      - name: Set up GCC
        uses: actions/setup-gcc@v3
        with:
          gcc-version: '12' # Укажите версию GCC, которую хотите использовать

      - name: Build
        run: make  # Запускаем Makefile для сборки проекта

      - name: Run Tests
        run: make run # Запускаем тесты, предполагая, что в Makefile есть цель "run"
