name: CI Pipeline

on: pull_request

jobs:
  check_formatting:
    name: Check Code Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install clang-format
        run: sudo apt-get install -y clang-format
        
      - name: Check formatting
        run: make check_fmt

  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: check_formatting
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make
          
      - name: Build and test
        run: |
          make all
          make test
          
      - name: Clean up
        run: make clean
