name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up GCC
      run: sudo apt-get update && sudo apt-get install -y gcc

    - name: Build
      run: make

    - name: Run Tests
      run: make run
