name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential clang-format

      - name: Build project
        run: make -C task_6/linked_list all

      - name: Run tests
        run: make -C task_6/linked_list test

      - name: Check format
        run: make -C task_6/linked_list check-format
        